const { Pet } = require('../models');

const petData = [
    {
        id: 1,
        owner_id: 1,
        name: 'Rocky',
        species: 'Dog',
        breed: 'Mixed',
        sex: 'Male Neutered',
        birthday: 'April 2nd, 2020',
        medical_history: 'Tooth issues but otherwise healthy!',
        medications: 'none',
        personality: 'Not aggresive and loves to play',
        caution: false,
        vet: 'Nope!',
        other: 'He has lots of energy!'
    },
    {
        id: 2,
        owner_id: 2,
        name: "Mischa",
        species: "cat",
        breed: "domestic shorthair",
        sex: "female spayed",
        birthday: "5.20.2020",
        medical_history: "no major medical history",
        medications: "no current medications",
        personality: "friendly",
        caution: false,
        vet: "bluepearl",
        other: "worm girl"
    },
    {
        id: 3,
        owner_id: 2,
        name: "Phoebe",
        species: "cat",
        breed: "domestic shorthair",
        sex: "female spayed",
        birthday: "5.15.2013",
        medical_history: "no major medical history",
        medications: "no current medications",
        personality: "friendly",
        caution: true,
        vet: "bluepearl",
        other: "fatty"
    },
    {
        id: 4,
        owner_id: 2,
        name: "Effie",
        species: "cat",
        breed: "domestic shorthair",
        sex: "female spayed",
        birthday: "5.17.2015",
        medical_history: "allergies/asthma",
        medications: "allergy shots every three weeks",
        personality: "friendly",
        caution: false,
        vet: "bluepearl",
        other: "shy girl"
    },
    {
        id: 5,
        owner_id: 3,
        name: "Deedee",
        species: "cat",
        breed: "domestic shorthair",
        sex: "female spayed",
        birthday: "3.16.2014",
        medical_history: "",
        personality: "friendly",
        caution: false,
        vet: "Riverside",
        other: "loud"
    },
    {
        id: 6,
        owner_id:  3,
        name: 'Dexter',
        species: 'cat',
        breed: 'domestic longhair',
        sex: 'male neutered',
        birthday: '3.16.2014',
        medical_history: '',
        medications: '',
        personality: 'friendly',
        caution: false,
        vet: 'Riverside',
        other: 'whoosh'
    },
    {
        id: 7,
        owner_id: 3,
        name: 'Bitey',
        species: 'cat',
        breed: 'domestic longhair',
        sex: 'male neutered',
        birthday: '7.14.2020',
        medical_history: '',
        medications: '',
        personality: 'evil',
        caution: true,
        vet: 'Riverside',
        other: 'awful'
    },
    {
        id: 8,
        owner_id: 3,
        name: 'Tuxedo',
        species: 'dog',
        breed: 'beagle-springer',
        sex: 'male neutered',
        birthday: '6.04.2008',
        medical_history: '',
        medications: '',
        personality: 'goofy',
        caution: false,
        vet: 'Riverside',
        other: 'adorable'
    },
    {
        id: 9,
        owner_id: 3,
        name: 'Prince',
        species: 'dog',
        breed: 'beagle-springer',
        sex: 'male neutered',
        birthday: '6.04.2009',
        medical_history: '',
        medications: '',
        personality: 'crazy',
        caution: true,
        vet: 'Riverside',
        other: 'nervous'
    },
    {
        id: 10,
        owner_id: 4,
        name: "Benji",
        species: "Dog",
        breed: "Chihuahua Terrier mix",
        sex: "Male neutered",
        birthday: "9-28-2012",
        medical_history: "severely broken right leg 6 years ago has arthritis",
        medications: "Takes CBD and a joint medication",
        personality: "friendly",
        caution: false,
        vet: "Forest Lake ",
        other: "Captain Benjamin Cribs"
    },
    {
        id: 11,
        owner_id: 4,
        name: "Kirby",
        species: "Dog",
        breed: "Dachshund Terrier mix",
        sex: "Male neutered",
        birthday: "5-8-2014",
        medical_history: "N/A",
        medications: "Takes CBD",
        personality: "friendly with humans hates other dogs",
        caution: false,
        vet: "Forest Lake ",
        other: "Turd"
    }
];

const seedPets = () => Pet.bulkCreate(petData);

module.exports = seedPets;